services:
  - type: web
    name: mernstack-blog
    runtime: node
    plan: free
    rootDir: week-10
    buildCommand: npm install && npm install -w Backend && npm install -w Frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
